@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"c:\Program Files\IAR Systems\Embedded Workbench 6.0_5.30_full\common\bin\cspybat" "c:\Program Files\IAR Systems\Embedded Workbench 6.0_5.30_full\430\bin\430proc.dll" "c:\Program Files\IAR Systems\Embedded Workbench 6.0_5.30_full\430\bin\430fet.dll"  %1 --plugin "c:\Program Files\IAR Systems\Embedded Workbench 6.0_5.30_full\430\bin\430bat.dll" --backend -B "--hardware_multiplier" "32" "--hwmult_type" "8" "-p" "c:\Program Files\IAR Systems\Embedded Workbench 6.0_5.30_full\430\config\MSP430F6638.ddf" "--core=430Xv2" "--data_model=small" "--iv_base" "0xFF80" "--no_wrap_around" "-d" "fet" "--erase_main_and_info" "--derivative" "MSP430F6638" "-lpt1" "--protocol" "automatic" "--eem" "EMEX_LARGE_5XX" "--connection" "ti_lpt" "--msp430_dll" "msp430.dll" "--vccDefault" "3.3" 


